<?php
$spock_slider_sc = spock_get_theme_option( 'front_page_title_shortcode' );
if ( ! empty( $spock_slider_sc ) && strpos( $spock_slider_sc, '[' ) !== false && strpos( $spock_slider_sc, ']' ) !== false ) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider
		<?php
		if ( spock_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
	">
	<?php
		// Add anchor
		$spock_anchor_icon = spock_get_theme_option( 'front_page_title_anchor_icon' );
		$spock_anchor_text = spock_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $spock_anchor_icon ) || ! empty( $spock_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $spock_anchor_icon ) ? ' icon="' . esc_attr( $spock_anchor_icon ) . '"' : '' )
									. ( ! empty( $spock_anchor_text ) ? ' title="' . esc_attr( $spock_anchor_text ) . '"' : '' )
									. ']'
		);
	}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode( $spock_slider_sc );
	?>
	</div>
	<?php

} else {

	?>
	<div class="front_page_section front_page_section_title
		<?php
		$spock_scheme = spock_get_theme_option( 'front_page_title_scheme' );
		if ( ! empty( $spock_scheme ) && ! spock_is_inherit( $spock_scheme ) ) {
			echo ' scheme_' . esc_attr( $spock_scheme );
		}
		echo ' front_page_section_paddings_' . esc_attr( spock_get_theme_option( 'front_page_title_paddings' ) );
		if ( spock_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
		"
		<?php
		$spock_css      = '';
		$spock_bg_image = spock_get_theme_option( 'front_page_title_bg_image' );
		if ( ! empty( $spock_bg_image ) ) {
			$spock_css .= 'background-image: url(' . esc_url( spock_get_attachment_url( $spock_bg_image ) ) . ');';
		}
		if ( ! empty( $spock_css ) ) {
			echo ' style="' . esc_attr( $spock_css ) . '"';
		}
		?>
	>
	<?php
		// Add anchor
		$spock_anchor_icon = spock_get_theme_option( 'front_page_title_anchor_icon' );
		$spock_anchor_text = spock_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $spock_anchor_icon ) || ! empty( $spock_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $spock_anchor_icon ) ? ' icon="' . esc_attr( $spock_anchor_icon ) . '"' : '' )
									. ( ! empty( $spock_anchor_text ) ? ' title="' . esc_attr( $spock_anchor_text ) . '"' : '' )
									. ']'
		);
	}
	?>
		<div class="front_page_section_inner front_page_section_title_inner
		<?php
		if ( spock_get_theme_option( 'front_page_title_fullheight' ) ) {
			echo ' spock-full-height sc_layouts_flex sc_layouts_columns_middle';
		}
		?>
			"
			<?php
			$spock_css      = '';
			$spock_bg_mask  = spock_get_theme_option( 'front_page_title_bg_mask' );
			$spock_bg_color_type = spock_get_theme_option( 'front_page_title_bg_color_type' );
			if ( 'custom' == $spock_bg_color_type ) {
				$spock_bg_color = spock_get_theme_option( 'front_page_title_bg_color' );
			} elseif ( 'scheme_bg_color' == $spock_bg_color_type ) {
				$spock_bg_color = spock_get_scheme_color( 'bg_color', $spock_scheme );
			} else {
				$spock_bg_color = '';
			}
			if ( ! empty( $spock_bg_color ) && $spock_bg_mask > 0 ) {
				$spock_css .= 'background-color: ' . esc_attr(
					1 == $spock_bg_mask ? $spock_bg_color : spock_hex2rgba( $spock_bg_color, $spock_bg_mask )
				) . ';';
			}
			if ( ! empty( $spock_css ) ) {
				echo ' style="' . esc_attr( $spock_css ) . '"';
			}
			?>
		>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$spock_caption = spock_get_theme_option( 'front_page_title_caption' );
				if ( ! empty( $spock_caption ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo ! empty( $spock_caption ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( $spock_caption, 'spock_kses_content' ); ?></h1>
					<?php
				}

				// Description (text)
				$spock_description = spock_get_theme_option( 'front_page_title_description' );
				if ( ! empty( $spock_description ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo ! empty( $spock_description ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( wpautop( $spock_description ), 'spock_kses_content' ); ?></div>
					<?php
				}

				// Buttons
				if ( spock_get_theme_option( 'front_page_title_button1_link' ) != '' || spock_get_theme_option( 'front_page_title_button2_link' ) != '' ) {
					?>
					<div class="front_page_section_buttons front_page_section_title_buttons">
					<?php
						spock_show_layout( spock_customizer_partial_refresh_front_page_title_button1_link() );
						spock_show_layout( spock_customizer_partial_refresh_front_page_title_button2_link() );
					?>
					</div>
					<?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}
